config/routes.rb
Rails.application.routes.draw do
  get 'errors/file_not_found'

  get 'errors/unprocessable'

  get 'errors/internal_server_error'

  match ":controller(/:action(/:id))", :via => [:get, :post]

  root 'welcome#index'

  get 'success' => 'welcome#success'
  get 'forward' => 'messages#forward', as: :forward
  get 'branding' => 'welcome#branding'

  get 'events' => 'events#index'

  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

end

app/models/event.rb
class Event < ActiveRecord::Base
  before_create :shorten_link

  def current?
    range = self.start_date..self.end_date
    now = Date.today
    range.cover?(now) or now < self.start_date
  end

  def self.current
    Event.all.sort_by{ :start_date }.select{ |event| event.current? }
  end

  def self.last_three
    Event.current.last(3)
  end

  def self.last_five
    Event.current.last(5)
  end

  def to_string
    name = self.name
    link = self.link

    "#{name}\n#{link}"
  end

  def self.humanize_date(date)
    date.strftime("%m/%d/%y")
  end

  private

  def shorten_link
    Bitly.use_api_version_3

    Bitly.configure do |config|
      config.api_version = 3
      config.access_token = ENV['BITLYAPI']
    end

    bitly = Bitly.client.shorten(self.link)

    self.link = bitly.short_url
  end
end

app/models/user.rb
require 'mandrill'

class User < ActiveRecord::Base
  validates :email, email: true, allow_blank: true
  validates :zipcode, :length => {:is => 5, :message => "Zip code must be 5 digits long."}, allow_blank: true
  validates :phone_no, :length => {:is => 10, :message => "Please enter a valid phone number."}, presence: true
  validates :phone_no, uniqueness: true

  before_validation(on: :create) do
    self.phone_no = phone_no.gsub(/\D/, "") if attribute_present?("phone_no")
  end 

  def send_text
    @client = Twilio::REST::Client.new ENV['TWILIOSID'], ENV['TWILIOTOKEN']

    body = "Welcome to What's Happening! " +
      "Messaging and Data rates may apply.\n" +
      "Here are some events that are happening soon!\n\n"

    Event.last_three.each do |event|
      body = body + event.to_string + "\n\n"
    end

    body = body + "Powered by GiveBackHack.\nhttp://givebackhack.com/"

    @client.messages.create(
      from: ENV['TWILIOPHONE'],
      to: self.phone_no,
      body: body
    )
  end

  def send_email
    mandrill = Mandrill::API.new ENV['MANDRILL_APIKEY']
    template_name = "welcome"

    template_content = [{"content"=>"example content", "name"=>"example name"}]
    message = {
      "from_name" => "What's Happening",
      "to" => [{"email" => self.email}]
    }

    result = mandrill.messages.send_template template_name, template_content, message
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def file_not_found
  	render :status => 400
  end

  def unprocessable
  	render :status => 422
  end

  def internal_server_error
  	render :status => 500
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.current
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def forward
    sender = params["From"]
    message = params["Body"]

    @client = Twilio::REST::Client.new ENV['TWILIOSID'], ENV['TWILIOTOKEN']

    keyword = message.split.first.downcase
    body = ""

    case keyword
    when "events"
      body = "Here are some events:\n\n"

      Event.last_five.each do |event|
        body = body + event.to_string + "\n\n"
      end
    when "help"
      body = "Text \"EVENTS\" to see the latest events"
    else
      body = "Sorry, I couldn't figure out what you were trying to say!\n" +
        "Try: EVENTS or HELP"
    end

    @client.messages.create(
      from: ENV['TWILIOPHONE'],
      to: sender,
      body: body
    )

    render nothing: true
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @user = User.new
  end

  def create
    @user = User.create(user_params)

    if @user.save
      redirect_to success_path

      unless @user.phone_no.nil?
        @user.send_text
      end

      unless @user.email.nil?
        @user.send_email
      end
    else
      redirect_to success_path, notice: "There was an error. Please try again."
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :phone_no)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/ez_messages_helper.rb
module EzMessagesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/_index.html.erb
<div class="color-bg" style="background: #00896C;">
  <div class="container">
    <div class="col-md-12">
      <h1>Events</h1>
      <p>Here are the events that are currently happening!</p>

      <div class="table-responsive">
        <table class="table">
          <thead>
            <tr>
              <td>Name</td>
              <td>Start Date</td>
              <td>End Date</td>
              <td>Location</td>
              <td>Link</td>
            </tr>
          </thead>
          <tbody>
            <% @events.each do |event| %>
              <tr>
                <td><%= event.name %></td>
                <td><%= Event.humanize_date event.start_date %></td>
                <td><%= Event.humanize_date event.end_date %></td>
                <td><%= event.location %></td>
                <td><%= link_to event.link, event.link %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<div id="wrapper" class="site">
  <div id="header">
    <%= render "welcome/header" %>
  </div>

  <div id="content">
    <%= render "index" %>
  </div>

  <div id="footer">
    <%= render "welcome/footer" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>What's Happening</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<% if current_page?(success_path) %>
  <body class="turquoise">
<% else %>
  <body>
<% end %>

<%= yield %>

</body>
</html>

app/views/messages/forward.html.erb
<h1>Messages#forward</h1>
<p>Find me in app/views/messages/forward.html.erb</p>

app/views/welcome/_content.html.erb
<div class="color-bg" style="background: #00896C; padding-bottom: 0;">
  <div class="container">
    <div class="col-sm-12">
      <h3>Get Involved</h3>

      <div class="row flex-vertical-align">
        <div class="col-sm-8">
          <p style="margin-bottom: 10%;">
            What&rsquo;s Happening is the best way to stay informed about family friendly events occurring in Columbus, Ohio. Each week a list of events tailored to your interests will be texted to your mobile device. These events will provide opportunities to interact with your community, meet new people, have fun and, most importantly, spend time with your family and friends. 
          </p>
        </div>

        <div class="col-sm-4 iphone-container">
          <%= image_tag "iphone.svg", class: "iphone" %>
        </div>
      </div>

    </div>
  </div>
</div>


<div class="color-bg" style="background: #59B6AF;">
  <div class="container flex-vertical-align">
    <div class="col-sm-8">
      <h3>Your schedule, delivered</h3>

      <p>
        With hectic schedules, finding the time to search event lists, plan evenings and weekends, and get everything prepared and situated gets lost in the everyday shuffle. However so, spending time with the individuals most important to you is fundamental. So, let us help you in finding the events that you can attend as a&nbsp;family!
      </p>
    </div>
    <div class="col-sm-4">
      <%= image_tag "family.svg", class: "family" %>
    </div>
  </div>
</div>

<div class="color-bg" style="background: #34495e;">
  <div class="container flex-vertical-align">
    <div class="col-sm-4">
      <%= image_tag "knowledge.svg", class: "knowledge" %>
    </div>

    <div class="col-sm-8">
      <h3>Knowledge is Power</h3>
      <p>
        What&rsquo;s Happening intends to bridge the gap between the desire to
        have fun and the events and activities to do so. With a city filled
        with festivals, museums, sporting events, and other activities, staying
        in because you weren't aware of an event is no longer an
        excuse.<br><br>So, What's Happening? Subscribe to find out.
      </p>
    </div>

  </div>
</div>

app/views/welcome/_footer.html.erb
<div class="container">
  <div class="col-xs-4">
    <%= link_to "https://www.facebook.com/whtshappening", :target => "_blank" do %>
    <i class="fa fa-facebook fa-2x" style="margin-right: 0.5em;"></i>
    <% end %>

    <%= link_to "https://twitter.com/whtsh/", :target => "_blank" do %>
    <i class="fa fa-twitter fa-2x"></i>
    <% end %>
  </div>

  <div class="col-sm-8 text-right">
    &copy; 2015 <%= image_tag "footer-logo.svg", class: "footer-logo" %>.
    Made with <i class="fa fa-heart"></i> in Columbus, OH
  </div>


</div>

app/views/welcome/_header.html.erb
<div class="container">
  <div class="col-md-12">
    <div id="navigation">
      <%= link_to root_path do %>
        <%= image_tag "logo.svg", id: "logo" %>
      <% end %>

      <ul>
        <li>About</li>
        <li><%= link_to "Events", events_path %></li>
      </ul>
    </div>

    <% if current_page? root_path %>
      <h2>Sign up for weekly texts about local family friendly events</h2>

      <%= form_for(@user, url: {action: "create"}) do |f| %>
      <div class="input-group input-group-lg">
        <%= f.text_field(:email, class: "form-control input-sm",
        placeholder: "user@email.com" ) %>
        <span class="input-group-btn" style="width:0px;"></span>

        <%= f.text_field(:phone_no, class: "form-control input-sm",
        style: "border-left: none", placeholder: "6141234567") %>

        <span class="input-group-btn">
          <%= f.submit "Subscribe", class: "btn btn-default",
          style: "border-left: none" %>
        </span>
      </div>
      <% end %>
    <% end %>

  </div>
</div>

app/views/welcome/branding.html.erb
<div id="wrapper" class="site">
  <div class="container">
    <div class="col-md-12">
      <h1>Branding</h1>

      <%= image_tag "logo.svg" %>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div id="wrapper" class="site">
  <div id="header">
    <%= render("header") %>
  </div>

  <div id="content">
   <%= render("content") %>
  </div>

  <div id="footer">
    <%= render("footer") %>
  </div>
</div>

app/views/welcome/success.html.erb
<div class="container center-flex">
  <div class="col-md-12 text-center" style="margin: 0 auto;">
    <%= link_to root_path do %>
      <%= image_tag "logo.svg", id: "logo", class: "success-image" %>
    <% end %>
    <% if flash[:notice] %>
      <h2><%= flash[:notice] %></h2>
    <% else %>
      <h2>Thank you for subscribing!</h2>
    <% end %>
  </div>
</div>

app/views/welcome/test.html.erb
Hello

<%= @email %>
<%= @phone %>